### ISSUE TITLE
Validation message not present for Direction widget

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/transportation-511#45]
On blank directions text box and clicking on 'Get Directions', observe that validation message is not generated after migrating to 3.10 API.
Also observed that sometimes clearing the text in search text box using double click event is not functional, mostly occurs after re-routing.

**Comment by lindsayking** [comment]
This app has been replaced by the [new Transportation 511](http://links.esri.com/stategovernment/help/transportation511).  No action required at this time.
