### ISSUE TITLE
Traffic Camera Image - Not filling popup

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/transportation-511#64]
Access http://203.199.47.84/transportation_511_V1.7/

-Click  Cameras from the Information Panel
-Select Beach - West (1-94) MP 1
-Note the image does not fill up the Popup
![version1 7popup](https://cloud.githubusercontent.com/assets/4106968/4260998/0aad98e4-3b59-11e4-85b8-1ac9e09a4e2b.png)

This is different from how it behaved before. Using this URL 

-http://tryitlive.arcgis.com/transportation511/

Using the same steps above, note the image fills the popup.
![previousversionpopup](https://cloud.githubusercontent.com/assets/4106968/4260990/cf47eb42-3b58-11e4-9f0b-b397e5ac1b7a.png)

**Comment by lindsayking** [comment]
This app has been replaced by the [new Transportation 511](http://links.esri.com/stategovernment/help/transportation511).  No action required at this time.
