### ISSUE TITLE
Routes within Buffer - Road Conditions

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/transportation-511#65]
-Generate Directions- Using the following Destinations

A: Fargo, North Dakota
B. Bismark, North Dakota

Note the route within the buffer (sitting directly under the blue graphic) is not reflected in the Road Conditions item

**Comment by lindsayking** [comment]
This app has been replaced by the [new Transportation 511](http://links.esri.com/stategovernment/help/transportation511).  No action required at this time.
