### ISSUE TITLE
iOS 8 Safari Issue -Scrolling does not work

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/transportation-511#77]
-Splash Screen Scroll is broken on iPad & iPhone  iOS 8.02
-511 information Scroll is broken on iPad & iPhone iOS 8.02
-Directions Scroll is broken on iPad & iPhone iOS 8.02
-Search Scroll is broken on iPad & iPhone iOS 8.02
-Information Scroll is broken on iPad & iPhone iOS 8.02

**Comment by lindsayking** [comment]
This app has been replaced by the [new Transportation 511](http://links.esri.com/stategovernment/help/transportation511).  No action required at this time.
